Added parameter to limit which contexts to return
mugoweb/mugo_i18n pull request #1
Opened 2016-10-21 15:08 UTC by alconasoftware

In the AMNH Spanish Translation project, some of the contexts exported by the script were not needed.  This created many translation strings that weren't needing translation, adding to the complexity of maintaining the translation file moving forward.  A parameter for the script was added to limit the returned contexts.

When the i18n function was embedded in a line of code, these translations were missed.  Therefore the regular expression was modified to pick up these instances.

2016-10-21 15:13 UTC, peterkeung commented
Looks like we have a tabs vs spaces issue. Perhaps we should have a follow-up commit to standardize on spaces.

2016-10-24 11:33 UTC, pkamps commented
Thanks for the pull request. I'll look into it very soon.

2016-10-24 15:54 UTC, alconasoftware commented
Re the space / tab issues.  I took a look at the file, and it appears that tabs were used in the original file, but my updates used spaces, so now we have a mix.  I can change it to all spaces if that is what is decided

2016-10-24 16:03 UTC, pkamps commented
I'd prefer to have this pull request using tabs. Then I would do another pull request to change all files from tabs to spaces.

2016-10-24 16:12 UTC, dougplant commented
+1 for all spaces all the time

2016-10-24 16:35 UTC, pkamps requested changes

2016-10-24 16:35 UTC, pkamps commented on scripts/create_translation_file.php
> +$contexts        = explode( ',', $targetContexts->value );
Could you rewrite this to:

$contexts = array();
if( $targetContexts->value )
{
    $contexts = explode( ',', $targetContexts->value );
}

2016-10-24 16:35 UTC, pkamps commented on scripts/create_translation_file.php
> +                    if( in_array( $instance[ 'context' ], $contexts, false ) || $contexts[ 0 ] == "" )
replace this line with:
if( empty( $contexts ) || in_array( $instance[ 'context' ], $contexts, false ) )

2016-10-24 18:35 UTC, alconasoftware commented
Made the changes requested by Philipp.  I've left the tabs for now until the pull is accepted.

2016-10-24 18:42 UTC, pkamps approved these changes

2016-10-24 18:42 UTC, merged

2016-10-24 18:43 UTC, pkamps commented
Great - thanks for that. What about the tabs -> spaces pull request - do you want to do this as well? ( crossing fingers :)

2016-10-25 17:01 UTC, alconasoftware commented
Yes - I will do the tabs to spaces.  There are tabs in all of the files.  Should I do a complete sweep of the entire repo?

2016-10-25 17:27 UTC, pkamps commented
I would not mind to change the entire repo. But it depends on our workload.